# Deploy static HTML/CSS/JS site to Azure Web App

name: Build and deploy static site to Azure Web App - sultanmuhammad

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: |
            index.html
            css/
            img/
            Sultan Muhammad-Resume.docx
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_63A64CB3477940C88BE5F21003318B12 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A16D3A721E184A22B9104090853BF94C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95A69480DA9A40D195162AF3573EA047 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sultanmuhammad'
          slot-name: 'Production'
          package: .
          